<a href="https://colab.research.google.com/github/Mounika2111/python-assignment/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
A = np.zeros((5,5))

# To find the memory size of any array we should multiply Size of the Array with its Item Size.
print("%d bytes" % (A.size * A.itemsize))

200 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
array = np.zeros(10)
array[4] = 1

print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
vector = np.arange(10,49)
print(vector,"\n")

# If 49 needs to be included the

vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
vector = np.arange(10,49)

print("Vector before reversed : ","\n",vector,"\n")
print("Vector before reversed : ","\n",vector[::-1])

Vector before reversed :  
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 

Vector before reversed :  
 [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
A = [1,2,0,0,4,0]
print("Indices of non-zero elements from [1,2,0,0,4,0] is : ","\n",np.nonzero(A))

Indices of non-zero elements from [1,2,0,0,4,0] is :  
 (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
Imat=np.eye(3,3)
print("The 3x3 Identity Matrix is : ","\n",Imat)

The 3x3 Identity Matrix is :  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
ran = np.random.random((3,3,3))
print("The 3x3x3 Array with Random Values","\n",ran)

The 3x3x3 Array with Random Values 
 [[[0.35021528 0.50515291 0.82821625]
  [0.22557173 0.42802588 0.92840394]
  [0.94881977 0.04662627 0.53630164]]

 [[0.80848119 0.07932229 0.4765997 ]
  [0.94783818 0.59512146 0.01533428]
  [0.4283631  0.90144383 0.83741782]]

 [[0.45580645 0.79045988 0.38757298]
  [0.04547006 0.08572372 0.24993333]
  [0.66296635 0.89962314 0.61687905]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
ran1 = np.random.random((10,10))
print("The Minimum Value is : ",ran1.min())
print("The Maximum Value is : ",ran1.max())

The Minimum Value is :  0.007891895921971814
The Maximum Value is :  0.9999259685141537


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
ran2 = np.random.random(30)
print("The mean value of the random vector of size 30 is : ",ran2.mean())

The mean value of the random vector of size 30 is :  0.5227978730625322


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print("2d array with 1 on the border and 0 inside : ","\n",Z)

2d array with 1 on the border and 0 inside :  
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print("A border (filled with 0's) around an existing array : ","\n",Z)

A border (filled with 0's) around an existing array :  
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
Z = np.diag(1+np.arange(4), k = -1)

print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
Checker = np.zeros ((8,8), dtype=int)

Checker[1::2, ::2]= 1
Checker[::2, 1::2] = 1

print (Checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
print ("In (6,7,8) shape array the index (x,y,z) of the 100th element is : ",np.unravel_index(100, (6,7,8)))

In (6,7,8) shape array the index (x,y,z) of the 100th element is :  (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
array1= np.array([[0,1], [1,0]])
Za = np.tile(array1,(4,4))

print ("Checkerboard 8x8 matrix using the tile function : ","\n",Za)

Checkerboard 8x8 matrix using the tile function :  
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
Norm = np.random.random((5,5))
Normmax, Normmin = Norm.max(), Norm.min()
mat= (Norm-Normmin)/(Normmax-Normmin)

print ("Normalized a 5x5 random matrix is :","\n",mat)

Normalized a 5x5 random matrix is : 
 [[1.         0.36178889 0.36497597 0.52121219 0.        ]
 [0.6757144  0.02407111 0.46938541 0.25053506 0.93228761]
 [0.45702151 0.91622122 0.18337744 0.74764488 0.15130954]
 [0.44836722 0.40238477 0.15538888 0.99374163 0.99448986]
 [0.91950643 0.9079782  0.47094732 0.18201149 0.03473903]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)

col = input()
print(color[col])
type(color)

blue
4


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
mat1= np.dot(np.ones((5,3)), np.ones((3,2)))

print (mat1)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
arr1 = np.arange(16)

print("If 3 and 8 Not to be included : ","\n")
arr1 [(arr1 >= 3) & (arr1 <= 8)] = (-1)
print(arr1,"\n")

arr2 = np.arange(16)
print("If 3 and 8 are to be included : ","\n")
arr2 [(arr2 > 3) & (arr2 < 8)] = (-1)
print(arr2)

arr3 = np.arange(16)
print("Or According to the hint : ","\n")
arr3 [(arr3 > 3) & (arr3 <= 8)] = (-1)
print(arr3)


If 3 and 8 Not to be included :  

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10 11 12 13 14 15] 

If 3 and 8 are to be included :  

[ 0  1  2  3 -1 -1 -1 -1  8  9 10 11 12 13 14 15]
Or According to the hint :  

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(np.sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(3) 
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z) # This expression is illegal

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [30]:
round = np.random.uniform(-10, +10, 10)
Rounds = np.copysign(np.ceil(np.abs(round)), round)

print(Rounds)

[ 2.  8.  8. -8. -2.  3.  9.  4.  3. -3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
A1 = np.arange(0, 20)
A2 = np.arange(15, 30)
CA = np.intersect1d(A1,A2)

print(CA)

[15 16 17 18 19]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [32]:
defaults = np.seterr(all="ignore")
Zd = np.ones(1) / 0
print(Zd)

# Back to Normal
_ = np.seterr(**defaults)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
#  No the expression is false

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [34]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday : ",yesterday)
print("Today : ",today)
print("Tomorrow : ",tomorrow)

Yesterday :  2022-09-16
Today :  2022-09-17
Tomorrow :  2022-09-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [35]:
mon = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(mon)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [36]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

print("Addision : ",np.add(A, B, out=B),"\n")
print("Division :",np.divide(A, 2, out=A),"\n")
print("Negative : ",np.negative(A, out=A),"\n")
print("Multiplication : ",np.multiply(A, B, out=A))

Addision :  [3. 3. 3.] 

Division : [0.5 0.5 0.5] 

Negative :  [-0.5 -0.5 -0.5] 

Multiplication :  [-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [37]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(np.trunc(Z))

[5. 9. 7. 1. 7. 1. 1. 2. 8. 2.]
[5. 9. 7. 1. 7. 1. 1. 2. 8. 2.]
[5. 9. 7. 1. 7. 1. 1. 2. 8. 2.]
[5 9 7 1 7 1 1 2 8 2]
[5. 9. 7. 1. 7. 1. 1. 2. 8. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [38]:
Z = np.zeros((5,5))
Z += np.arange(5)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [39]:
def generate(): 
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(), dtype=float, count=-1)

print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [40]:
za = np.linspace(0,1,10,endpoint=True)[1:-1]

print(za)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [41]:
so = np.random.random(10)
so.sort()

print(so)

[0.00476576 0.17136534 0.27644729 0.36496544 0.39322456 0.59975753
 0.69375116 0.79567649 0.79901983 0.95201459]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [42]:
Z = np.arange(25)
np.add.reduce(Z)


300

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [43]:
A = np.random.randint(0,5,10)
B = np.random.randint(0,20,10)
close = np.allclose(A,B)
equal = np.array_equal(A,B)

print(equal)
print(close)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [44]:
imm = np.zeros(10)
imm.flags.writeable = False
imm[0] = 1 # Proof

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [45]:
po = np.random.random((10,2))
X,Y = po[:,0], po[:,1]

R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

print(R,"\n")
print(T)

[0.24582244 0.96581596 0.98055399 0.75494881 1.21519946 0.55987162
 0.69073351 0.89222498 0.67331144 0.77484603] 

[1.53201664 0.91670706 0.75688298 0.32799955 0.71518468 0.40190691
 0.37918857 0.872509   0.63453767 0.7048239 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [46]:
ma = np.random.random(10)
ma[ma.argmax()] = 0

print(ma)

[0.31651849 0.03752033 0.13652242 0.30650907 0.77632455 0.66351943
 0.25437374 0.08013289 0.         0.47981232]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [47]:
z = np.zeros((10, 10), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

print(z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [48]:
x = np.random.random((10, 10))
y = np.random.random((10, 10))

c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)

print(np.linalg.det(c))

[[-3.51176370e+08 -1.57009834e+08  8.82477316e+15 -3.86682823e+17
   6.54145924e+14 -7.62774967e+12 -8.31246643e+13  2.24067277e+10
  -1.28739695e+13 -3.16085029e+13]
 [ 8.67965560e+14 -1.35569612e+14 -5.45463672e+12 -1.30531911e+10
   2.58873483e+16  1.11071947e+14  4.29236634e+15 -3.62178721e+13
   3.96517459e+13 -2.10351446e+08]
 [-2.16971092e+13  3.37086212e+13  2.43099095e+14  1.50751841e+12
  -7.17888686e+13  5.11554914e+12  8.51347052e+11  6.85313642e+16
   8.41475265e+13  3.81213559e+14]
 [ 1.20790715e+13 -1.13037650e+14  7.75919914e+14  1.33265586e+13
   2.48336119e+14 -1.09231810e+11  2.94109614e+13 -7.26879683e+15
  -8.97517181e+14  3.13948365e+13]
 [-8.16353289e+08 -4.78882704e+14 -1.21774039e+09  4.05583842e+13
   2.28424082e+13 -2.09050063e+13 -7.62302753e+08 -1.69803023e+15
  -3.76753392e+14 -6.37735838e+14]
 [-2.65408700e+13 -4.51164247e+14  5.36249476e+15  2.47526310e+16
  -1.45342055e+15 -2.34379352e+13  2.63166009e+13  1.40446233e+14
   1.22013020e+12  3.21903213e+13

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [49]:
print("For Integer : ")
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max,"\n")

print("For Float : ")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps,"\n")

For Integer : 
-128
127 

-2147483648
2147483647 

-9223372036854775808
9223372036854775807 

For Float : 
-3.4028235e+38
3.4028235e+38
1.1920929e-07 

-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16 



#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [50]:
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
Z = np.ones((25,50))

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [51]:
Z = np.arange(10)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()

print(Z[index])

9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [52]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [53]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)

[[0.         0.32797746 0.56883884 0.72903692 0.62971008 0.1426954  0.3071702  0.46229661 0.33098329 0.20318106 0.20135883 0.72364848 0.37398192 0.43738012 0.33928674 0.2152409  0.58665894 0.654288   0.63109777 0.17979066 0.58901197 0.32490183 0.15447878 0.73222733 0.54353262 0.85253716 0.49615515 0.38404418 0.32092627 0.44513801 0.45803667 0.34212134 0.76055326 0.32290266 0.0573678  0.70399361 0.78147901 0.21710749 0.18859596 0.58720243 0.8428088  0.18108557 0.10786183 0.32211143 0.7325857  0.01953971 0.67760814 0.056824   0.18854511 0.3623062  0.47391738 0.38378984 0.31601357 0.70632132 0.53136362 0.83521359 0.47261492 0.60995695 0.15250459 0.56685682 0.43437313 0.22442608 0.36485009 0.04693143 0.56462282 0.52430743 0.59706145 0.66794922 0.51539417 0.49685901 0.76228575 0.52888438 0.40409707 0.2171191  0.67039798 0.23739215 0.08842363 0.41117194 0.51808518 0.75090943 0.19285675 0.56488763 0.49930189 0.25295669 0.44510006 0.66836477 0.74648474 0.456799   0.83855579 0.60277259 0.496892

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [54]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)

print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [56]:
Z = np.arange(9).reshape(3,3)

print("numerate : ")
for index, value in np.ndenumerate(Z):
    print(index, value)


print("\n","index : ")  
for index in np.ndindex(Z.shape):
    print(index, Z[index])

numerate : 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

 index : 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [57]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [58]:
n = 10
p = 3
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [59]:
X = np.random.rand(10, 20)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.03773505  0.18519287  0.01503254 -0.14171789 -0.33723951  0.30485614  0.22525431  0.16888221  0.40660063  0.11366489 -0.27957071 -0.11400954 -0.47150222  0.36192572  0.22496699 -0.40100945 -0.35661713  0.29609169 -0.11040278 -0.05266371]
 [ 0.10715004 -0.27821898 -0.03794999 -0.34717436 -0.04856147 -0.24811746  0.35688167 -0.38432915 -0.08359651 -0.08883551 -0.33720587  0.31959928  0.01875095  0.10127992  0.537792   -0.12375393  0.24187358  0.51887598  0.06028562 -0.28474579]
 [ 0.46148911 -0.01047762  0.25781113  0.07822519 -0.47558725 -0.08973479  0.31423533 -0.20554112  0.2464301   0.36776936  0.1463862  -0.05047094 -0.44941786 -0.24946082  0.17783854 -0.21035391  0.49259054 -0.03463062 -0.28904154 -0.47805904]
 [-0.08666991  0.24543228  0.26839944 -0.35759485  0.27144621  0.11717915  0.36538867 -0.34915987 -0.43387992  0.24611032 -0.41449591  0.27101135 -0.37267945  0.2343631  -0.23210281  0.47057794  0.12735771 -0.31908706  0.31052241 -0.3621188 ]
 [-0.2221104   0.36450927  0

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [60]:
Z = np.random.randint(0,10,(5,5))
print("Before Sorted : ","\n",Z,"\n")

print("After Sorted the nth column : ","\n",Z[Z[:,1].argsort()])

Before Sorted :  
 [[9 8 2 1 2]
 [0 8 9 6 1]
 [6 4 7 3 5]
 [3 7 0 3 7]
 [5 3 1 7 7]] 

After Sorted the nth column :  
 [[5 3 1 7 7]
 [6 4 7 3 5]
 [3 7 0 3 7]
 [9 8 2 1 2]
 [0 8 9 6 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [61]:
Z = np.random.randint(0,5,(5,12))

print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [62]:
Z = np.random.uniform(0,5,10)
z = 1
m = Z.flat[np.abs(Z - z).argmin()]

print(m)

0.7761435673623285


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [63]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10),"Range_10")
print (Z.name)

Range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [65]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))

print(Z)

[3. 2. 2. 5. 4. 1. 3. 5. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [66]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [67]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))

print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [68]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)

print(sum)

[[54 54 51 40]
 [44 61 56 62]
 [43 64 40 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [69]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)

D_means = D_sums / D_counts

print(D_means)

[0.47601576 0.6257236  0.565609   0.58227156 0.28930841 0.48097786 0.40504124 0.51911461 0.45081479 0.66353062]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [70]:
A = np.random.randint(0,20,(5,5))
B= np.random.randint(0,20,(5,5))

print(np.diag(np.dot(A, B)))

[396 462 127 460 508]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [71]:
Z = np.array([1,2,3,4,5])
nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [72]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [73]:
A = np.arange(25).reshape(5,5)
print("Before Swap : ","\n",A,"\n")

A[[0,1]] = A[[1,0]]
print("After Swap : ","\n",A)

Before Swap :  
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

After Swap :  
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [74]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)

print(G)

[( 1, 37) ( 1, 41) ( 3, 38) ( 3, 60) ( 4, 15) ( 4, 79) ( 5, 21) ( 5, 47) (12, 34) (12, 55) (13, 20) (13, 89) (15, 79) (20, 89) (21, 47) (31, 38) (31, 68) (34, 55) (37, 41) (38, 60) (38, 68) (42, 62) (42, 86) (45, 51) (45, 85) (51, 85) (62, 86) (72, 78) (72, 97) (78, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [75]:
C = np.bincount([1,1,2,3,4,4,6,7,8,8,9,9])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6 7 8 8 9 9]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [76]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(50)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [77]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
    
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [78]:
Z = np.random.randint(0,20,100)

print('Negating a boolean: ')
print(np.logical_not(Z, out=Z),"\n")

Z = np.random.uniform(-1.0,1.0,10)

print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

Negating a boolean: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

Change the sign of float inplace: 
[ 0.21585406 -0.46505499 -0.64658063 -0.91240545  0.37033872 -0.35851455 -0.16076906  0.09212697  0.56649326 -0.5739186 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [79]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.89605409  7.85401533  2.42887014  3.58965992  3.83444696  2.83263983 14.82334875 17.62990612  5.800399   18.08550722]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [80]:
P0 = np.random.uniform(-10, 10, (10,5))
P1 = np.random.uniform(-10,10,(10,5))
p = np.random.uniform(-10, 10, (10,5))

print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[21.81234528 14.13476214 17.97879271 12.10980012 14.24062231 16.82226431  6.13360883 16.6026792  14.1862578  23.55889176]
 [14.97729819  6.19287745 16.73811011  9.38049563  9.67952796 10.96954716  7.1829229  11.08553498 12.92727032 16.63418228]
 [16.76973086 13.52439375 15.27245051 15.06387717 14.45698319 15.54033904  6.05433771 10.81265396 15.37578369 20.0705829 ]
 [ 6.28473903 10.35821234 20.97895152 18.90899581 13.73160753 11.57743254 18.95403134  9.88913892 20.45877429  3.29714143]
 [18.12626702 16.80584095  9.95054057  8.47432428 26.02458915 16.58824639  8.64262718 14.20896859 24.50427172 21.6082827 ]
 [16.36636411 12.48531288 21.66527054 14.95331867 11.18853274  4.50428154 18.03097422 18.03278049 10.11931725 14.31389493]
 [16.13878131 21.53613791 10.98971327 18.26209933 27.07162452 16.77459268 18.63752752 17.137781   22.81090133 20.44593627]
 [17.93325871 15.90121888 13.58112667 15.84564355 18.5422616  12.55083986 13.50923799 15.14722356  8.69137512 20.24566135]
 [18.80187535 15

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [81]:
Z = np.random.randint(0,15,(10,20))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]

print(Z,"\n")
print(R)

[[13  6  2  2 12  1  1  0 11  0  0 12 13 10  3 11 11  4 11 13]
 [ 4  9  1  6 12  8  4 14 12  6  2 11  4  8 13  7 12 13  0  0]
 [11 11  6 11 10  1  7  0 14 14  2 10 14  7 11  8  1  0 14 14]
 [ 0  4  9  9 13 12  2 13  9  8  7 12  3 13 12  7  5  6  4  6]
 [10  3  7  8  3  3  0  1  0  5  1  9  9 12 12 12  0  9  3 11]
 [ 0  6  0 12  9  7  5  4 10 12  1  7  8  9 13  8  6 10  1  4]
 [12  4  5  7  1 10  0  8  7 11  1 14  7  5 13 10 10 12  9  9]
 [ 9  3  5  2  2 11 12  3 11 10  5 12  6  7 13  1  9 11  2 11]
 [ 5  3  6  6  7 11  4 12 12  5  0  5 14  0  9 13 11 10  3  2]
 [ 6  1  0  0 11 14  7  9 10  0  4 12  9 11  1  6 14 14  2 10]] 

[[ 0  0  0  0  0]
 [ 0 13  6  2  2]
 [ 0  4  9  1  6]
 [ 0 11 11  6 11]
 [ 0  0  4  9  9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [82]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)

print ('Before stride: ')
print (Z,"\n")
print ('after strides: ')
print(R)

Before stride: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [83]:
Z = np.random.uniform(0,2,(5,5))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)

print ("The rank of the matrix is : ",rank)

The rank of the matrix is :  5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [84]:
Z = np.random.randint(0,10,100)

print (Z)
print('rank:', np.bincount(Z).argmax())

[1 7 9 0 5 2 3 7 5 5 3 7 8 7 5 6 0 2 6 8 6 1 5 8 4 1 0 5 9 5 1 9 6 0 9 9 0 0 2 3 1 1 1 9 2 3 1 6 2 2 4 4 6 8 4 8 4 0 7 1 3 1 1 9 7 4 8 6 2 3 8 8 5 1 7 7 4 9 7 7 1 1 1 9 8 3 6 5 9 2 8 3 5 4 0 1 2 0 2 3]
rank: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [85]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print(C)

[[[[2 0 3]
   [2 3 1]
   [1 2 1]]

  [[0 3 1]
   [3 1 3]
   [2 1 3]]

  [[3 1 4]
   [1 3 4]
   [1 3 3]]

  [[1 4 2]
   [3 4 2]
   [3 3 4]]

  [[4 2 0]
   [4 2 0]
   [3 4 3]]

  [[2 0 2]
   [2 0 1]
   [4 3 2]]

  [[0 2 1]
   [0 1 0]
   [3 2 4]]

  [[2 1 4]
   [1 0 4]
   [2 4 0]]]


 [[[2 3 1]
   [1 2 1]
   [0 3 0]]

  [[3 1 3]
   [2 1 3]
   [3 0 4]]

  [[1 3 4]
   [1 3 3]
   [0 4 1]]

  [[3 4 2]
   [3 3 4]
   [4 1 2]]

  [[4 2 0]
   [3 4 3]
   [1 2 1]]

  [[2 0 1]
   [4 3 2]
   [2 1 3]]

  [[0 1 0]
   [3 2 4]
   [1 3 0]]

  [[1 0 4]
   [2 4 0]
   [3 0 2]]]


 [[[1 2 1]
   [0 3 0]
   [0 2 0]]

  [[2 1 3]
   [3 0 4]
   [2 0 1]]

  [[1 3 3]
   [0 4 1]
   [0 1 3]]

  [[3 3 4]
   [4 1 2]
   [1 3 3]]

  [[3 4 3]
   [1 2 1]
   [3 3 2]]

  [[4 3 2]
   [2 1 3]
   [3 2 1]]

  [[3 2 4]
   [1 3 0]
   [2 1 2]]

  [[2 4 0]
   [3 0 2]
   [1 2 3]]]


 [[[0 3 0]
   [0 2 0]
   [2 1 4]]

  [[3 0 4]
   [2 0 1]
   [1 4 3]]

  [[0 4 1]
   [0 1 3]
   [4 3 3]]

  [[4 1 2]
   [1 3 3]
   [3 3 3]]

  [[1 2 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [86]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 14  9 13  4]
 [14  4  9  4  8]
 [ 9  9  4 42  4]
 [13  4 42  2  9]
 [ 4  8  4  9  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [87]:
p, n = 100, 200
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

[[20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]
 [20000.]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [88]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [89]:
def iterate(Z):
   
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [90]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [91]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [92]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [93]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.11 s ± 8.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
59.6 ms ± 726 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
49.7 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [94]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [95]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]

print(Z,"\n")
print(U)

[[1 1 0]
 [0 2 4]
 [4 3 4]
 [3 1 4]
 [4 1 3]
 [1 4 0]
 [0 1 3]
 [1 0 1]
 [3 4 4]
 [0 3 0]] 

[[1 1 0]
 [0 2 4]
 [4 3 4]
 [3 1 4]
 [4 1 3]
 [1 4 0]
 [0 1 3]
 [1 0 1]
 [3 4 4]
 [0 3 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [96]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [97]:
Z = np.random.randint(0,2,(6,4))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(Z,"\n")
print(uZ)

[[0 1 0 0]
 [0 0 0 1]
 [1 0 1 1]
 [1 0 1 1]
 [0 1 0 1]
 [0 0 0 1]] 

[[0 0 0 1]
 [0 1 0 0]
 [0 1 0 1]
 [1 0 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [98]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A),"\n" )      
print(np.einsum('i,i->i', A, B),"\n") 
print(np.einsum('i,i', A, B),"\n")    
print(np.einsum('i,j->ij', A, B))

5.071761510931966 

[0.03538756 0.22626335 0.01174049 0.12337767 0.60760091 0.57102054 0.09151833 0.38009517 0.04713956 0.1681114 ] 

2.2622549797174374 

[[0.03538756 0.25073446 0.0667085  0.19809235 0.58957714 0.40385821 0.47410069 0.4667147  0.13437042 0.11034766]
 [0.03193381 0.22626335 0.06019791 0.17875899 0.53203575 0.36444257 0.42782954 0.42116441 0.12125617 0.09957798]
 [0.0062281  0.04412849 0.01174049 0.03486364 0.10376376 0.0710778  0.08344026 0.08214035 0.02364878 0.01942085]
 [0.0220404  0.15616471 0.041548   0.12337767 0.36720578 0.25153463 0.29528369 0.29068348 0.0836898  0.06872773]
 [0.03646938 0.25839958 0.06874783 0.20414817 0.60760091 0.41620442 0.48859426 0.48098248 0.13847821 0.11372106]
 [0.05003495 0.35451682 0.09432005 0.28008543 0.83361104 0.57102054 0.67033733 0.65989418 0.18998814 0.15602204]
 [0.00683106 0.04840068 0.01287712 0.03823888 0.11380939 0.07795902 0.09151833 0.09009257 0.02593828 0.02130103]
 [0.02881984 0.20419961 0.0543278  0.16132757 0.480155

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

print(r[1:],"\n")
print(r_int,"\n")
print(x_int,"\n")
print(y_int)

[1.00000000e-01 2.00994225e-01 3.03948099e-01 4.09773428e-01 5.19310334e-01 6.33316917e-01 7.52465988e-01 8.77347271e-01 1.00847317e+00 1.14628646e+00 1.29116861e+00 1.44344797e+00 1.60340735e+00 1.77129076e+00 1.94730924e+00 2.13164591e+00 2.32446017e+00 2.52589132e+00 2.73606151e+00 2.95507828e+00 3.18303664e+00 3.42002084e+00 3.66610588e+00 3.92135873e+00 4.18583938e+00 4.45960178e+00 4.74269456e+00 5.03516168e+00 5.33704304e+00 5.64837490e+00 5.96919031e+00 6.29951948e+00 6.63939009e+00 6.98882753e+00 7.34785520e+00 7.71649464e+00 8.09476576e+00 8.48268698e+00 8.88027538e+00 9.28754684e+00 9.70451612e+00 1.01311970e+01 1.05676022e+01 1.10137439e+01 1.14696332e+01 1.19352807e+01 1.24106962e+01 1.28958890e+01 1.33908678e+01 1.38956409e+01 1.44102161e+01 1.49346005e+01 1.54688013e+01 1.60128248e+01 1.65666773e+01 1.71303646e+01 1.77038924e+01 1.82872658e+01 1.88804900e+01 1.94835697e+01 2.00965094e+01 2.07193135e+01 2.13519861e+01 2.19945311e+01 2.26469523e+01 2.33092533e+01 2.3981437

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [100]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [101]:
X = np.random.randn(100) 
N = 1000 

idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [5,95])

print(confint)

[-0.27628787  0.0625312 ]
